server:
  port: 8081
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://116.62.188.101:3306/wc_answer_test?useUnicode=true&characterEncoding=utf8
    username: root
    password: Njsyc@456
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  resources:
    static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.answer.domain





