server:
  port: 8081
  context-path: /
spring:
  datasource:
    #url: jdbc:mysql://116.62.188.101:3306/wc_answer?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://116.62.188.101:3306/wc_answer_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Njsyc@456
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:/pages/
    mode: LEGACYHTML5
  redis:
    host: 47.100.229.122
    port: 7379
    password: lgh_lul@163.com
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.answer.domain
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql




